# Generated by Django 4.2.9 on 2026-05-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LRPFutures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous", models.FloatField(null=True)),
                ("symbol", models.CharField(max_length=50, null=True)),
                ("grouping_date", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=50, null=True)),
                ("commodity", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "lrp_futures",
            },
        ),
        migrations.CreateModel(
            name="WASDEReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wasde_number", models.IntegerField(null=True)),
                ("report_date", models.DateField(null=True)),
                ("report_title", models.CharField(max_length=200, null=True)),
                ("attribute", models.CharField(max_length=200, null=True)),
                ("commodity", models.CharField(max_length=100, null=True)),
                ("region", models.CharField(max_length=100, null=True)),
                ("market_year", models.CharField(max_length=20, null=True)),
                ("proj_est_flag", models.CharField(max_length=20, null=True)),
                ("value", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=100, null=True)),
                ("release_date", models.DateField(null=True)),
                ("forecast_year", models.IntegerField(null=True)),
                ("forecast_month", models.IntegerField(null=True)),
                ("market_date", models.CharField(max_length=50, null=True)),
                ("is_latest_two_dates", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "wasde_reports",
                "indexes": [
                    models.Index(
                        fields=["report_date", "commodity"],
                        name="wasde_repor_report__3d3e29_idx",
                    ),
                    models.Index(
                        fields=["commodity", "attribute"],
                        name="wasde_repor_commodi_526990_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Slaughter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("commodity", models.CharField(max_length=100, null=True)),
                ("class_name", models.CharField(max_length=100, null=True)),
                ("period", models.CharField(max_length=50, null=True)),
                ("slaughter", models.FloatField(null=True)),
                ("week_ago", models.FloatField(null=True)),
                ("year_ago", models.FloatField(null=True)),
                ("week_to_date", models.FloatField(null=True)),
                ("current_year_to_date", models.FloatField(null=True)),
                ("previous_year_to_date", models.FloatField(null=True)),
                ("pct_change", models.FloatField(null=True)),
                ("week_of_year", models.FloatField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("monday_of_week", models.DateField(null=True)),
                ("slaughter_date", models.DateField(null=True)),
                ("volume", models.FloatField(null=True)),
                ("source", models.CharField(default="harvest3", max_length=20)),
            ],
            options={
                "db_table": "slaughter",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="slaughter_report__e7395c_idx"
                    ),
                    models.Index(
                        fields=["commodity", "year"],
                        name="slaughter_commodi_a44ce9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NearbyFutures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("purchase_type", models.CharField(max_length=100, null=True)),
                ("price_5day", models.FloatField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("year", models.IntegerField(null=True)),
                ("wtd_avg", models.FloatField(null=True)),
                ("avg", models.FloatField(null=True)),
            ],
            options={
                "db_table": "nearby_futures",
                "indexes": [
                    models.Index(
                        fields=["report_date", "name"],
                        name="nearby_futu_report__eba157_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LRPQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=100, null=True)),
                ("coverage_level_percent", models.FloatField(null=True)),
                ("coverage_price", models.FloatField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("endorsement_length", models.IntegerField(null=True)),
                ("expected_ending_value", models.FloatField(null=True)),
                ("head_count", models.IntegerField(null=True)),
                ("livestock_rate", models.FloatField(null=True)),
                ("per_head_premium", models.FloatField(null=True)),
                ("per_cwt_premium", models.FloatField(null=True)),
                ("producer_premium", models.IntegerField(null=True)),
                ("subsidy_percent", models.FloatField(null=True)),
                ("target_weight", models.FloatField(null=True)),
                ("futures_price", models.FloatField(null=True)),
                ("cme_premium", models.FloatField(null=True)),
                ("strike", models.IntegerField(null=True)),
                ("grouping_date", models.IntegerField(null=True)),
                ("weekdays_to_expiration", models.IntegerField(null=True)),
                ("expiration_date", models.DateField(null=True)),
                ("sales_effective_date", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "lrp_quotes",
                "indexes": [
                    models.Index(
                        fields=["commodity", "coverage_level_percent"],
                        name="lrp_quotes_commodi_c2c372_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FuturesEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=100, null=True)),
                ("month", models.CharField(max_length=20, null=True)),
                ("year", models.IntegerField(null=True)),
                ("trading_day", models.DateField(null=True)),
                ("close", models.FloatField(null=True)),
                ("commodity_month", models.CharField(max_length=50, null=True)),
                ("month_name", models.CharField(max_length=20, null=True)),
                ("week_of_year", models.FloatField(null=True)),
                ("symbol", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "futures_endpoint",
                "indexes": [
                    models.Index(
                        fields=["trading_day", "commodity"],
                        name="futures_end_trading_f9aff2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CutoutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("attribute", models.CharField(max_length=100, null=True)),
                ("value", models.FloatField(null=True)),
                ("trend", models.FloatField(null=True)),
                ("week_of_year", models.CharField(max_length=20, null=True)),
                ("year", models.IntegerField(null=True)),
                ("index_by_year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "cutout_values",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="cutout_valu_report__d45a84_idx"
                    ),
                    models.Index(
                        fields=["attribute"], name="cutout_valu_attribu_8a887d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CattlePrimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("primal_desc", models.CharField(max_length=100, null=True)),
                ("choice_600_900", models.FloatField(null=True)),
                ("select_600_900", models.FloatField(null=True)),
                ("week_of_year", models.IntegerField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("start_of_week", models.DateField(null=True)),
                ("end_of_week", models.DateField(null=True)),
            ],
            options={
                "db_table": "cattle_primal",
                "indexes": [
                    models.Index(
                        fields=["report_date", "primal_desc"],
                        name="cattle_prim_report__9c6bc8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CashCattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("class_description", models.CharField(max_length=100, null=True)),
                ("selling_basis", models.CharField(max_length=100, null=True)),
                ("grade_description", models.CharField(max_length=100, null=True)),
                ("weighted_avg_price", models.FloatField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("index_by_year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "cash_cattle",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="cash_cattle_report__a94796_idx"
                    ),
                    models.Index(
                        fields=["class_description", "selling_basis"],
                        name="cash_cattle_class_d_e17cff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarcassWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("for_date_begin", models.DateField(null=True)),
                ("purchase_type", models.CharField(max_length=100, null=True)),
                ("head_count", models.IntegerField(null=True)),
                ("avg_net_price", models.FloatField(null=True)),
                ("avg_carcass_weight", models.FloatField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("index_by_year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "carcass_weights",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="carcass_wei_report__37f314_idx"
                    )
                ],
            },
        ),
    ]
