# Generated by Django 4.2.9 on 2026-05-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PorkPrimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("commodity", models.CharField(max_length=100, null=True)),
                ("value", models.FloatField(null=True)),
                ("week_of_year", models.IntegerField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("start_of_week", models.DateField(null=True)),
                ("end_of_week", models.DateField(null=True)),
            ],
            options={
                "db_table": "pork_primals",
                "indexes": [
                    models.Index(
                        fields=["report_date", "commodity"],
                        name="pork_primal_report__175e43_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CowHarvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("class_name", models.CharField(max_length=100, null=True)),
                ("volume", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=50, null=True)),
                ("year", models.IntegerField(null=True)),
                ("index_by_year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "cow_harvest",
                "indexes": [
                    models.Index(
                        fields=["report_date", "class_name"],
                        name="cow_harvest_report__fb2f14_idx",
                    )
                ],
            },
        ),
    ]
