# Generated by Django 4.2.9 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_porkprimal_cowharvest"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarvestUSDA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("for_date_begin", models.DateField(null=True)),
                ("avg_carcass_weight", models.FloatField(null=True)),
                ("avg_backfat", models.FloatField(null=True)),
                ("wtd_avg_base", models.FloatField(null=True)),
                ("wtd_avg_net_price", models.FloatField(null=True)),
                ("week_of_year", models.IntegerField(null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "harvest_usda",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="harvest_usd_report__1c2191_idx"
                    )
                ],
            },
        ),
    ]
