# Generated by Django 4.2.9 on 2026-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_harvestusda"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedFutures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=20, null=True)),
                ("symbol", models.CharField(max_length=20, null=True)),
                ("contract_month", models.CharField(max_length=10, null=True)),
                ("trade_date", models.DateField(null=True)),
                ("open_price", models.FloatField(null=True)),
                ("high_price", models.FloatField(null=True)),
                ("low_price", models.FloatField(null=True)),
                ("close_price", models.FloatField(null=True)),
                ("volume", models.FloatField(null=True)),
            ],
            options={
                "db_table": "feed_futures",
                "indexes": [
                    models.Index(
                        fields=["commodity", "trade_date"],
                        name="feed_future_commodi_9cb46a_idx",
                    )
                ],
            },
        ),
    ]
