# Generated by Django 4.2.9 on 2026-05-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_feedfutures"),
    ]

    operations = [
        migrations.CreateModel(
            name="SowHarvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(null=True)),
                ("volume", models.FloatField(null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "sow_harvest",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="sow_harvest_report__102d7a_idx"
                    )
                ],
            },
        ),
    ]
